create table curso (id bigint generated by default as identity, categoria varchar(255), nome varchar(255), primary key (id));
create table resposta (id bigint generated by default as identity, data_criacao timestamp, mensagem varchar(255), solucao boolean not null, fk_usuario_id bigint, fk_topico_id bigint, primary key (id));
create table topico (id bigint generated by default as identity, data_criacao timestamp, mensagem varchar(255), status varchar(255), titulo varchar(255), fk_usuario_id bigint, fk_curso_id bigint, primary key (id));
create table usuario (id bigint generated by default as identity, nome varchar(255),
senha varchar(255), email varchar(255), ativo boolean default true , primary key (id));
create table perfil (id bigint generated by default as identity, nome varchar(255), primary key (id));
create table usuario_perfil (fk_usuario_id bigint not null, fk_perfil_id bigint not null);
create table permissao (id bigint generated by default as identity, descricao varchar(255), nome varchar(255), primary key (id));
create table perfil_permissao (fk_perfil_id bigint not null, fk_permissao_id bigint not null);
